version: '3'
services:
    r0:
        image: bftsmart
        build: .
        restart: always
        command: sh -c 'sleep 1 && sh runscripts/startReplicaYCSB.sh 0'
        
    r1:
        image: bftsmart
        restart: always
        command: sh -c 'sleep 5 && sh runscripts/startReplicaYCSB.sh 1'

    r2:
        image: bftsmart
        restart: always
        command: sh -c 'sleep 8 && sh runscripts/startReplicaYCSB.sh 2'
        
    r3:
        image: bftsmart
        restart: always
        command: sh -c 'sleep 11 && sh runscripts/startReplicaYCSB.sh 3'
    

    loader:
        image: bftsmart
        command: sh -c 'sleep 20 && sh runscripts/ycsbLoader.sh'
        environment:

    client:
        image: bftsmart
        command: sh -c 'sleep 150 && sh runscripts/ycsbClient.sh'
   