version: '3'
services:
    r0:
        image: bftsmart
        build: .
        restart: "no"
        # restart: always
        command: sh -c 'sleep 1 && sh runscripts/smartrun.sh bftsmart.demo.counter.DurableCounterServer 0'
        environment:
        - JAVA_OPTS=-Xms2G -XX:+UseG1GC            

    r1:
        image: bftsmart
        restart: "no"
        command: sh -c 'sleep 5 && sh runscripts/smartrun.sh bftsmart.demo.counter.DurableCounterServer 1'
        environment:
        - JAVA_OPTS=-XX:+UseG1GC

    r2:
        image: bftsmart
        restart: "no"
        command: sh -c 'sleep 10 && sh runscripts/smartrun.sh bftsmart.demo.counter.DurableCounterServer 2'
        environment:
        - JAVA_OPTS=-XX:+UseG1GC

    r3:
        image: bftsmart
        restart: "no"
        command: sh -c 'sleep 15 && sh runscripts/smartrun.sh bftsmart.demo.counter.DurableCounterServer 3'
        environment:
        - JAVA_OPTS=-XX:+UseG1GC


    client0:
        image: bftsmart
        command: sh -c 'sleep 20 && sh runscripts/smartrun.sh bftsmart.demo.counter.CounterClient 1001 1 108'

#    client1:
#        image: bftsmart
#        command: sh -c 'sleep 20 && sh runscripts/smartrun.sh bftsmart.demo.counter.CounterClient 2001 1 50'

