version: '3'
services:
    r0:
        image: bftsmart
        build: .
        restart: "no"
        command: sh -c 'sleep 1 && sh runscripts/startDurableReplicaYCSB.sh 0'
        environment:
        - JAVA_OPTS=-Xms2G -XX:+UseG1GC
        - RECORDCOUNT=1008


    r1:
        image: bftsmart
        restart: "no"
        command: sh -c 'sleep 5 && sh runscripts/startDurableReplicaYCSB.sh 1'
        environment:
        - JAVA_OPTS=-XX:+UseG1GC
        - RECORDCOUNT=1008

    r2:
        image: bftsmart
        restart: "no"
        command: sh -c 'sleep 10 && sh runscripts/startDurableReplicaYCSB.sh 2'
        environment:
        - JAVA_OPTS=-XX:+UseG1GC
        - RECORDCOUNT=1008
    
    r3:
        image: bftsmart
        restart: "no"
        command: sh -c 'sleep 15 && sh runscripts/startDurableReplicaYCSB.sh 3'
        environment:
        - JAVA_OPTS=-XX:+UseG1GC
        - RECORDCOUNT=1008



    loader:
        image: bftsmart
        command: sh -c 'cp config/workloads/workloada.compose config/workloads/workloada && sleep 20 && sh runscripts/ycsbLoader.sh'
        environment:
        - RECORDCOUNT=1008
        - CLIENTID=1000
        - OPERATIONS=100

    # client:
    #     image: bftsmart
    #     command: sh -c 'sleep 150 && sh runscripts/ycsbClient.sh'
    #     environment:
    #     - RECORDCOUNT=1008
    #     - CLIENTID=1000
    #     - OPERATIONS=108
    #     - EXECUTION_TIME=0
